import pandas as pd
import pytest
from datetime import datetime
from main import _generate_synthetic_fallback


def test_generate_synthetic_fallback_end_date():
    """
    Test that the synthetic data generated by _generate_synthetic_fallback
    has its latest timestamp within the last 3 business days of the current date.
    This ensures the pipeline doesn't fail the 'Price Freshness Check'.
    """
    prices, macro = _generate_synthetic_fallback()
    
    # 檢查是否為 DataFrame
    assert isinstance(prices, pd.DataFrame)
    assert isinstance(macro, pd.DataFrame)
    
    # 取出最新日期
    latest_date_prices = prices["timestamp"].max()
    latest_date_macro = macro["timestamp"].max()
    
    # 取得今天
    today = pd.Timestamp.today().normalize()
    
    # 差距不能超過 5 天 (涵蓋週末與連續假期)
    diff_prices = (today - latest_date_prices).days
    assert diff_prices <= 5, f"Prices data is too old! Latest date is {latest_date_prices.date()}, but today is {today.date()}"
    
    # Macro 的延遲較大（因為按月發布 + delay），但其資料應至少涵蓋到最近一兩個月內
    # 這裡我們放寬檢查，只要不超過 120 天即可，或者檢查 sim_end 是否正確
    diff_macro = (today - latest_date_macro).days
    assert diff_macro <= 120, f"Macro data is too old! Latest date is {latest_date_macro.date()}, but today is {today.date()}"


def test_generate_synthetic_fallback_length():
    """
    Test that the synthetic data covers at least 4 years of history,
    which is required by the feature engineer and models.
    """
    prices, _ = _generate_synthetic_fallback()
    earliest_date = prices["timestamp"].min()
    latest_date = prices["timestamp"].max()
    
    years_diff = (latest_date - earliest_date).days / 365.25
    assert years_diff >= 4.0, f"Synthetic data should cover at least 4 years. Got {years_diff:.1f} years."

