"""
execution/broker_base.py — Broker Adapter Abstraction Layer
=============================================================

Defines the interface contract that every broker adapter must satisfy.
All concrete implementations (simulated paper-trading, live Moomoo API,
FIX-protocol brokers, etc.) inherit from ``BrokerBase`` and implement
its abstract methods.

Data-flow position in the Nexus Quant OS pipeline::

    MoE Router → Portfolio Optimizer → Risk Firewall
        → **BrokerBase.reconcile()** → **BrokerBase.execute()**

Design Notes
------------
- No external broker SDK dependencies — adapters implement raw REST / FIX.
- All monetary values are in USD unless stated otherwise.
- ``OrderIntent`` carries a human-readable ``reason`` field so the
  LLM-driven decision journal can audit every trade.

Author : Nexus Quant OS — Execution Engineering Division
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from typing import Literal


# ═════════════════════════════════════════════════════════════════════
# 1. DATA CLASSES
# ═════════════════════════════════════════════════════════════════════

@dataclass(frozen=True)
class AccountSnapshot:
    """Point-in-time snapshot of the brokerage account.

    Attributes
    ----------
    equity : float
        Total account value (cash + market value of all positions).
    cash : float
        Uninvested cash balance.
    buying_power : float
        Available buying power (may exceed cash in margin accounts).
    timestamp : datetime
        UTC timestamp when this snapshot was captured.
    """

    equity: float
    cash: float
    buying_power: float
    timestamp: datetime


@dataclass(frozen=True)
class Position:
    """Single instrument position held in the account.

    Attributes
    ----------
    symbol : str
        Ticker symbol (e.g. ``"AAPL"``).
    qty : float
        Number of shares/units held.  Positive = long, negative = short.
    avg_cost : float
        Volume-weighted average cost basis per share.
    current_price : float
        Latest market price per share.
    market_value : float
        ``qty * current_price``.
    unrealized_pl : float
        ``market_value - (qty * avg_cost)``.
    unrealized_pl_pct : float
        Percentage unrealized P&L relative to cost basis.
    """

    symbol: str
    qty: float
    avg_cost: float
    current_price: float
    market_value: float
    unrealized_pl: float
    unrealized_pl_pct: float


@dataclass(frozen=True)
class OrderIntent:
    """Desired trade generated by the reconciliation engine.

    An ``OrderIntent`` is a *request* — it may be rejected, partially
    filled, or modified by risk checks before becoming an ``OrderResult``.

    Attributes
    ----------
    symbol : str
        Ticker symbol to trade.
    side : Literal['BUY', 'SELL']
        Direction of the trade.
    qty : float
        Number of shares/units to trade (always positive).
    reason : str
        Human-readable rationale for this trade (auditable).
    """

    symbol: str
    side: Literal["BUY", "SELL"]
    qty: float
    reason: str


@dataclass(frozen=True)
class OrderResult:
    """Outcome of an executed (or attempted) order.

    Attributes
    ----------
    symbol : str
        Ticker symbol that was traded.
    side : str
        ``'BUY'`` or ``'SELL'``.
    qty : float
        Number of shares/units filled.
    filled_price : float
        Volume-weighted average fill price.
    commission : float
        Total commission charged for this fill (USD).
    timestamp : datetime
        UTC timestamp of the fill.
    order_id : str
        Unique order identifier (broker-assigned or internal UUID).
    status : Literal['FILLED', 'REJECTED', 'CANCELLED']
        Final status of the order.
    """

    symbol: str
    side: str
    qty: float
    filled_price: float
    commission: float
    timestamp: datetime
    order_id: str
    status: Literal["FILLED", "REJECTED", "CANCELLED"]


# ═════════════════════════════════════════════════════════════════════
# 2. ABSTRACT BASE CLASS
# ═════════════════════════════════════════════════════════════════════

class BrokerBase(ABC):
    """Abstract interface for all broker adapters.

    Every concrete broker (paper-trading simulator, live REST adapter,
    FIX bridge, etc.) **must** implement these six methods.

    Thread-safety is NOT guaranteed — callers should serialise access
    or use per-thread instances.

    Usage
    -----
    >>> class MyBroker(BrokerBase):
    ...     def get_account(self) -> AccountSnapshot: ...
    ...     # ... implement remaining abstract methods ...
    """

    # ── Account & Position queries ────────────────────────────────

    @abstractmethod
    def get_account(self) -> AccountSnapshot:
        """Return a point-in-time snapshot of the brokerage account.

        Returns
        -------
        AccountSnapshot
            Current equity, cash, buying power, and timestamp.
        """

    @abstractmethod
    def get_positions(self) -> list[Position]:
        """Return all open positions in the account.

        Returns
        -------
        list[Position]
            One ``Position`` per held instrument.  Empty list if flat.
        """

    # ── Order lifecycle ───────────────────────────────────────────

    @abstractmethod
    def reconcile(
        self,
        target_weights: dict[str, float],
    ) -> list[OrderIntent]:
        """Compare current holdings to target weights and produce orders.

        The reconciler computes the delta between the current portfolio
        and the desired allocation, then emits a list of ``OrderIntent``
        objects sorted with sells first (to free cash) then buys.

        Parameters
        ----------
        target_weights : dict[str, float]
            Mapping of ``symbol → target_weight`` where weight is a
            fraction of total portfolio equity (e.g. ``{"AAPL": 0.25}``).

        Returns
        -------
        list[OrderIntent]
            Trade intents to reach the target allocation.
        """

    @abstractmethod
    def execute(
        self,
        intents: list[OrderIntent],
    ) -> list[OrderResult]:
        """Submit order intents for execution.

        Implementations should simulate or route orders, apply slippage
        and commission models, and return fill results.

        Parameters
        ----------
        intents : list[OrderIntent]
            Orders to execute (typically from ``reconcile()``).

        Returns
        -------
        list[OrderResult]
            One result per intent (filled, rejected, or cancelled).
        """

    # ── Market status ─────────────────────────────────────────────

    @abstractmethod
    def is_market_open(self) -> bool:
        """Check whether the primary exchange is currently in session.

        Returns
        -------
        bool
            ``True`` if the market is open for regular trading.
        """

    @abstractmethod
    def get_portfolio_value(self) -> float:
        """Return total portfolio value (equity) in USD.

        This is a convenience shortcut equivalent to
        ``self.get_account().equity``.

        Returns
        -------
        float
            Current total portfolio equity.
        """
